# Generated by Django 3.1.3 on 2020-11-30 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitterApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='timeStamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
