# Generated by Django 3.1.3 on 2020-11-30 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twitterApp', '0006_auto_20201130_1446'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet',
            name='author',
        ),
    ]
