# Generated by Django 3.1.3 on 2020-11-30 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitterApp', '0007_remove_tweet_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='author',
            field=models.CharField(default='user123', max_length=100),
        ),
    ]
