# Generated by Django 3.1.3 on 2020-11-30 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twitterApp', '0010_auto_20201130_1830'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tweet',
            old_name='tags',
            new_name='tag',
        ),
    ]
