# Generated by Django 3.1.3 on 2020-12-01 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twitterApp', '0011_auto_20201130_1853'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tweet',
            old_name='tag',
            new_name='tags',
        ),
    ]
