# Generated by Django 3.1.3 on 2020-12-01 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitterApp', '0012_auto_20201130_1931'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
