# Generated by Django 3.1.3 on 2020-12-01 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitterApp', '0013_tweet_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='likes',
            field=models.IntegerField(),
        ),
    ]
